### ISSUE TITLE
ampahlos fails to build on openSUSE systems

### ISSUE THREAD

**Issue by mnhauke** [dankamongmen/omphalos#36]
omphalos (v0.99.12) fails to build on openSUSE systems (tested Tumbleweed and Leap 15.2).
Both come with ncurses version 6.1.

```
[   27s] src/ui/ncurses/ncurses.c: In function 'mandatory_cleanup':
[   27s] src/ui/ncurses/ncurses.c:353:12: error: lvalue required as left operand of assignment
[   27s]   353 |     stdscr = NULL;
[   27s]       |            ^
[   27s] src/ui/ncurses/ncurses.c: In function 'ncurses_setup':
[   27s] src/ui/ncurses/ncurses.c:410:12: error: lvalue required as left operand of assignment
[   27s]   410 |   ESCDELAY = 100;
[   27s]       |            ^
[   27s] src/ui/ncurses/ncurses.c: In function 'main':
[   27s] src/ui/ncurses/ncurses.c:680:23: error: lvalue required as unary '&' operand
[   27s]   680 |     mandatory_cleanup(&stdscr);
[   27s]       |                       ^
[   27s] src/ui/ncurses/ncurses.c:685:24: error: lvalue required as unary '&' operand
[   27s]   685 |   if(mandatory_cleanup(&stdscr)){
[   27s]       |                        ^
[   27s] make: *** [Makefile:783: out/src/ui/ncurses/ncurses.o] Error 1
```

Full buildlog:
[omphalos-openSUSE-Tumbleweed-buildlog.txt](https://github.com/dankamongmen/omphalos/files/5139002/omphalos-openSUSE-Tumbleweed-buildlog.txt)

**Comment by dankamongmen** [comment]
I'll get on this ASAP; thanks for the report! BTW I do not currently recommend packaging Omphalos, due to the following bug:

https://github.com/dankamongmen/omphalos/issues/28

I can't demonstrate that this is not a dangerous security vulnerability; it really needs to be fixed (especially since omphalos typically runs with at least `CAP_NET_ADMIN`, and listens to raw packet sockets). I intend to fix this before the year is out, but my energies are focused on notcurses and growlight at this moment.

With that said, if you want to package it, you're welcome to do so, and either way I'll get this fixed ASAP.

**Comment by dankamongmen** [comment]
So the `ESCDELAY` comes down to SUSE's ncurses, which appears not to export `ESCDELAY` as a mutable variable. That's fine; I'm gonna remove that code. This will transition to Notcurses soon, where the `ESCDELAY` is neither relevant nor made available. I'm guessing that SUSE is building NCURSES with `--with-reentrant`.

I believe I've got this fixed. Incoming!

**Comment by dankamongmen** [comment]
This issue is resolved in head, and will be present in the next release. Please reopen if you're still seeing problems. Thanks!

**Comment by mnhauke** [comment]
It's fixed in head. Thanks!
